#!/bin/sh

cc=${CC:-gcc}

cflags="-static -Wl,--gc-sections"
cflags="$cflags -Ofast -pipe -flto"
cflags="$cflags -ffunction-sections -fdata-sections"
cflags="$cflags -g0 -fno-unwind-tables -s"
cflags="$cflags -fno-asynchronous-unwind-tables"
cflags="$cflags -Wall -Wno-variadic-macros"

cflags="-std=c89 -pedantic $cflags $CFLAGS"

$cc $cflags linux.c -o namae
